DemonCRUD/Models/Livro.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DemonCRUD.Models {
    public class Livro {
        public int Id { get; set; }
        public string Titulo { get; set; }
        public string Autor { get; set; }
        public int AnoEdicao { get; set; }
        public decimal Valor { get; set; }
        public Genero Genero { get; set; }
        public int GeneroId { get; set; }


    }
}

DemonCRUD/Controllers/LivrosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Linq.Dynamic;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DemonCRUD.AcessoDados;
using DemonCRUD.Models;

namespace DemonCRUD.Controllers
{
    public class LivrosController : Controller
    {
        private LivroContexto db = new LivroContexto();

        // GET: Livros
        public ActionResult Index()
        {
           
            return View();
        }

        public JsonResult Listar(string searchPhrase,int current = 1, int rowCount = 5) {
            string chave = Request.Form.AllKeys.Where(k => k.StartsWith("sort")).First();
            string ordenacao = Request[chave];
            string campo = chave.Replace("sort[", String.Empty).Replace("]", String.Empty);
            var livros = db.Livros.Include(l => l.Genero);

            int total = livros.Count();

            if (!String.IsNullOrWhiteSpace(searchPhrase)) {
                int ano = 0;
                int.TryParse(searchPhrase, out ano);

                decimal valor = 0.0m;
                decimal.TryParse(searchPhrase, out valor);
                livros = livros.Where("Titulo.Contains(@0) OR Autor.Contains(@0) OR AnoEdicao == @1 OR Valor = @2", searchPhrase, ano, valor);
            }

            string campoOrdenacao = String.Format("{0} {1}", campo, ordenacao);

            var livrosPaginados = livros.OrderBy(campoOrdenacao).Skip((current -1)* rowCount).Take(rowCount);

            return Json(new {
                rows = livrosPaginados.ToList(),
                current = current,
                rowCount = rowCount,
                total = total
            }
            ,JsonRequestBehavior.AllowGet);
        }
        // GET: Livros/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Livro livro = db.Livros.Find(id);
            if (livro == null)
            {
                return HttpNotFound();
            }
            return PartialView(livro);
        }

        // GET: Livros/Create
        public ActionResult Create()
        {
            ViewBag.GeneroId = new SelectList(db.Generos, "Id", "Nome");
            return PartialView();
        }

        // POST: Livros/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult Create([Bind(Include = "Id,Titulo,Autor,AnoEdicao,Valor,GeneroId")] Livro livro)
        {
            if (ModelState.IsValid) {
                db.Livros.Add(livro);
                db.SaveChanges();

                return Json(new { resultado = true, mensagem = "Livro cadastrado com sucesso" });
            } else {
                IEnumerable<ModelError> erros = ModelState.Values.SelectMany(item => item.Errors);

                return Json(new { resultado = false, mensagem = erros });
            }           
        }

        // GET: Livros/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Livro livro = db.Livros.Find(id);
            if (livro == null)
            {
                return HttpNotFound();
            }
            ViewBag.GeneroId = new SelectList(db.Generos, "Id", "Nome", livro.GeneroId);
            return PartialView(livro);
        }

        // POST: Livros/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Titulo,Autor,AnoEdicao,Valor,GeneroId")] Livro livro)
        {
            if (ModelState.IsValid)
            {
                db.Entry(livro).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.GeneroId = new SelectList(db.Generos, "Id", "Nome", livro.GeneroId);
            return View(livro);
        }

        // GET: Livros/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Livro livro = db.Livros.Find(id);
            if (livro == null)
            {
                return HttpNotFound();
            }
            return PartialView(livro);
        }

        // POST: Livros/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Livro livro = db.Livros.Find(id);
            db.Livros.Remove(livro);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DemonCRUD/Views/Livros/Create.cshtml
@model DemonCRUD.Models.Livro

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("Create","Livros",FormMethod.Post, new { id = "formCrud" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Livro</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Titulo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Titulo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Titulo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Autor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Autor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Autor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AnoEdicao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AnoEdicao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AnoEdicao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Valor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Valor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Valor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GeneroId, "GeneroId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("GeneroId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.GeneroId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="button" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@Scripts.Render("~/bundles/jqueryval")

<script type="text/javascript">
    var btnAcao = $("input[type='button']");
    var formulario = $("#formCrud");

    btnAcao.on("click", submeter);

    function submeter() {
        if (formulario.valid()) {
            var url = formulario.prop("action");
            var metodo = formulario.prop("method");

            var dadosFormulario = formulario.serialize();

            $.ajax({
                url: url,
                type: metodo,
                data: dadosFormulario,
                success: tratarRetorno
            });
        }
    }

    function tratarRetorno(resultadoServidor) {
        if (resultadoServidor.resultado) {
            toastr['success'](resultadoServidor.mensagem);

            $("#minhaModal").modal("hide");

            $("#gridDados").bootgrid("reload");

        } else {
            toastr['error'](resultadoServidor.mensagem);
        }
    }
</script>

DemonCRUD/Views/Livros/Delete.cshtml
@model DemonCRUD.Models.Livro

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Livro</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Genero.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Genero.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Titulo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Autor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Autor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AnoEdicao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AnoEdicao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Valor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Valor)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

DemonCRUD/Views/Livros/Details.cshtml
@model DemonCRUD.Models.Livro

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Livro</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Genero.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Genero.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Titulo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Autor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Autor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AnoEdicao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AnoEdicao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Valor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Valor)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

DemonCRUD/Views/Livros/Edit.cshtml
@model DemonCRUD.Models.Livro

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Livro</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Titulo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Titulo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Titulo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Autor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Autor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Autor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AnoEdicao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AnoEdicao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AnoEdicao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Valor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Valor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Valor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GeneroId, "GeneroId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("GeneroId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.GeneroId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

DemonCRUD/Views/Livros/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    <a href="#" class="btn btn-success" data-action="Create">
        <span class="glyphicon glyphicon-plus"></span>
        Novo Livro
    </a>
</p>

<table id="gridDados">
    <thead>
        <tr>
            <th data-column-id="Titulo" data-order="asc">Titulo</th>
            <th data-column-id="Autor">Autor</th>
            <th data-column-id="AnoEdicao">Ano da Edição</th>
            <th data-column-id="Valor">Valor</th>
            <th data-formatter="acoes"></th>
        </tr>
    </thead>
</table>

<!-- Modal -->
<div class="modal fade" id="minhaModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <div id="conteudoModal"></div>
            </div>
        </div>
    </div>
</div>



@section scripts{
    <script src="~/Scripts/jquery.bootgrid.js"></script>
    <script type="text/javascript">

        var controller = "Livros";

        $(document).ready(configurarControles);

        function configurarControles() {

            var traducao = {
                infos: "Exibindo {{ctx.start}} até {{ctx.end}} de {{ctx.total}} registros.",
                loading: "Carregando",
                noResults: "Não ha dados para exibir",
                refresh: " Atualizar",
                search: "Pesquisar"
            };

            var grid = $("#gridDados").bootgrid(
                {
                    ajax: true,
                    url: "@Url.Action("Listar")",
                    labels: traducao,
                    searchSettings: {
                        characters: 4
                    },
                    formatters: {
                        "acoes": function (column, row) {
                            return "<a href='#' class='btn btn-info' data-acao='Details' data-row-id='"+ row.Id+"'><span class='glyphicon glyphicon-list'></span></a> " +
                                   "<a href='#' class='btn btn-warning' data-acao='Edit' data-row-id='" + row.Id + "'><span class='glyphicon glyphicon-edit'></span></a> " +
                                   "<a href='#' class='btn btn-danger' data-acao='Delete' data-row-id='" + row.Id + "'><span class='glyphicon glyphicon-trash'></span></a>";
                        }
                    }
                });

            grid.on("loaded.rs.jquery.bootgrid", function () {
                grid.find("a.btn").each(function (index, elemento) {

                    var botaoDeAcao = $(elemento);
                    var acao = botaoDeAcao.data("acao");
                    var idEntidade = botaoDeAcao.data("row-id");

                    botaoDeAcao.on("click", function () {

                        abrirModal(acao, idEntidade);

                    });


                });
            });

            $("a.btn").click(function () {
                var acao = $(this).data("action");
                abrirModal(acao);
            })
        }

        function abrirModal(acao, parametro) {
            var url = "/{ctrl}/{acao}/{parametro}";

            url = url.replace("{ctrl}", controller);
            url = url.replace("{acao}", acao);

            if (parametro != null) {
                url = url.replace("{parametro}", parametro);
            } else {
                url = url.replace("{parametro}", "");
            }
            $("#conteudoModal").load(url, function () {
                $("#minhaModal").modal('show');
            });

            
        }


    </script>

}